config/routes.rb
Rails.application.routes.draw do
  get 'show_date_time/display'

  resources :olympics

  root 'show_date_time#display'

end

app/models/olympic.rb
class Olympic < ActiveRecord::Base
  validates :athlete_name,  presence: true, allow_blank: false
  validates :country,  presence: true, allow_blank: false
  validates :medal_type, :inclusion => { :in => ["gold", "silver", "bronze"] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/olympics_controller.rb
class OlympicsController < ApplicationController
  before_action :set_olympic, only: [:show, :edit, :update, :destroy]

  # GET /olympics
  # GET /olympics.json
  def index
    @olympics = Olympic.all
  end

  # GET /olympics/1
  # GET /olympics/1.json
  def show
  end

  # GET /olympics/new
  def new
    @olympic = Olympic.new
  end

  # GET /olympics/1/edit
  def edit
  end

  # POST /olympics
  # POST /olympics.json
  def create
    @olympic = Olympic.new(olympic_params)

    respond_to do |format|
      if @olympic.save
        format.html { redirect_to @olympic, notice: 'Olympic was successfully created.' }
        format.json { render :show, status: :created, location: @olympic }
      else
        format.html { render :new }
        format.json { render json: @olympic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /olympics/1
  # PATCH/PUT /olympics/1.json
  def update
    respond_to do |format|
      if @olympic.update(olympic_params)
        format.html { redirect_to @olympic, notice: 'Olympic was successfully updated.' }
        format.json { render :show, status: :ok, location: @olympic }
      else
        format.html { render :edit }
        format.json { render json: @olympic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /olympics/1
  # DELETE /olympics/1.json
  def destroy
    @olympic.destroy
    respond_to do |format|
      format.html { redirect_to olympics_url, notice: 'Olympic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_olympic
      @olympic = Olympic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def olympic_params
      params.require(:olympic).permit(:athlete_name, :event, :country, :medal_type, :event_date)
    end
end

app/controllers/show_date_time_controller.rb
class ShowDateTimeController < ApplicationController
  def display
    @title = "Takehome Midterm -- Show Date and Time"
    t = Time.now
    @date_time = t
    if t.hour >= 6 && t.hour <= 18
      @timeimg = "sun.png"
    else
      @timeimg = "moon.jpg"
    end

    if t.mon == 1
      @monthname = "January"
      @monthimg = "jan.jpg"
    elsif t.mon == 2
      # it's == not =
      @monthname = "February"
      @monthimg = "feb.jpg"
    elsif t.mon == 3
      @monthname = "March"
      @monthimg = "mar.jpg"
    elsif t.mon == 4
      # no such keyword elseif
      @monthname = "April"
      @monthimg = "apr.jpg"
    elsif t.mon == 5
      @monthname = "May"
      @monthimg = "may.jpg"
    elsif t.mon == 6
      @monthname = "June"
      @monthimg = "jun.jpg"
    elsif t.mon == 7
      @monthname = "July"
      @monthimg = "jul.jpg"
    elsif t.mon == 8
      @monthname = "August"
      @monthimg = "aug.jpg"
    elsif t.mon == 9
      @monthname = "September"
      @monthimg = "sep.jpg"
    elsif t.mon == 10
      @monthname = "October"
      @monthimg = "oct.jpg"
    elsif t.mon == 11
      @monthname = "November"
      @monthimg = "nov.jpg"
    elsif t.mon == 12
      @monthname = "December"
      @monthimg = "dec.jpg"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/olympics_helper.rb
module OlympicsHelper
end

app/helpers/show_date_time_helper.rb
module ShowDateTimeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<!-- add namespace to html tag -->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <!-- missing ending title tag-->
  <title><%= @title %></title>
  <!-- It's stylesheet_link_tag not stylesheet_tag -->
  <%= stylesheet_link_tag "application" %>
  <!-- missing ending head tag-->
</head>
<body>
<h2><%= @title %></h2>
<!-- output should enclosed in <\%= %> -->
<%= yield %>
</body>
</html>

app/views/olympics/_form.html.erb
<%= form_for(@olympic) do |f| %>
  <% if @olympic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@olympic.errors.count, "error") %> prohibited this olympic from being saved:</h2>

      <ul>
      <% @olympic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :athlete_name %><br>
    <%= f.text_field :athlete_name %>
  </div>
  <div class="field">
    <%= f.label :event %><br>
    <%= f.text_field :event %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :medal_type %><br>
    <%= f.text_field :medal_type %>
  </div>
  <div class="field">
    <%= f.label :event_date %><br>
    <%= f.date_select :event_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/olympics/edit.html.erb
<h1>Editing olympic</h1>

<%= render 'form' %>

<%= link_to 'Show', @olympic %> |
<%= link_to 'Back', olympics_path %>

app/views/olympics/index.html.erb
<h1>Listing olympics</h1>

<table>
  <thead>
    <tr>
      <th>Athlete name</th>
      <th>Event</th>
      <th>Country</th>
      <th>Medal type</th>
      <th>Event date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @olympics.each do |olympic| %>
      <tr>
        <td><%= olympic.athlete_name %></td>
        <td><%= olympic.event %></td>
        <td><%= olympic.country %></td>
        <td><%= olympic.medal_type.titleize %></td>
        <td><%= olympic.event_date %></td>
        <td><%= link_to 'Show', olympic %></td>
        <td><%= link_to 'Edit', edit_olympic_path(olympic) %></td>
        <td><%= link_to 'Destroy', olympic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Olympic', new_olympic_path %>

app/views/olympics/new.html.erb
<h1>New olympic</h1>

<%= render 'form' %>

<%= link_to 'Back', olympics_path %>

app/views/olympics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Athlete name:</strong>
  <%= @olympic.athlete_name %>
</p>

<p>
  <strong>Event:</strong>
  <%= @olympic.event %>
</p>

<p>
  <strong>Country:</strong>
  <%= @olympic.country %>
</p>

<p>
  <strong>Medal type:</strong>
  <%= @olympic.medal_type %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @olympic.event_date %>
</p>

<%= link_to 'Edit', edit_olympic_path(@olympic) %> |
<%= link_to 'Back', olympics_path %>

app/views/show_date_time/display.html.erb
<p>Date and Time:
  <!-- it's @date_time not @datetime-->
  <%= @date_time %>
  <!-- should use /> instead of > for br tag to comply with XHTML-->
  <br />
  <%= image_tag @timeimg, :class => "img" %>
<!-- missing ending p tag-->
</p>

<p>Month: <%= @monthname %><br />
  <!-- if you want to output to page, you use <\%= not <\% -->
  <!-- it's image_tag not image-tag -->
  <%= image_tag @monthimg, :class => "img" %></p>